services:
  ocr_service:
    #    build: .
    image: ghcr.io/kivvi3412/ocr_panel:latest
    container_name: OCR_Panel
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
    restart: always
    volumes:
      - ocr_panel:/app
    ports:
      - "7860:7860"

volumes:
  ocr_panel: